filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.log

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "tcp:///host_docker/docker.sock"

instrumentation:
  enabled: true
  environment: production
  hosts:
    - "http://apm-server:8200"
  #secret_token: AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDkwODk1MDExODc6OVNwSVZLLU9SVnE4d1RqU2RhYmpYdw