version: '2.2'
services:
 
  webappfinal:
    container_name: webappfinal
    image: luizfigueira/webappfinal:latest
    build:
      context: ./src
      dockerfile: WebAppFinal/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://*:83
    ports:
        - "83:83"
    depends_on:
        - webapifinal

  webapifinal:
    container_name: webapifinal
    image: luizfigueira/webapifinal:latest
    build:
      context: ./src
      dockerfile: WebApiFinal/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://*:84
    ports:
        - "84:84"