heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://kibana:5601
    - http://webappfinal:83

- type: icmp
  schedule: '@every 5s'
  hosts:
    - kibana
    - webappfinal
    - webapimysql

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  protocol: "https"
  ssl.enabled: true
  ssl.verification_mode: none

