apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqldata
  labels: 
    type: local
spec:
  #storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /C/Backup/Dev/Cursos/AWS-ECS-Teste-Final/volume
    #type: Directory