apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  clusterIP: 10.96.0.3
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30008
  type: LoadBalancer
