version: '3'

services:

  sql-server:
    image: luizfigueira/sql-server:latest
    container_name: sql-server
    build: 
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"     

  webappfinal:
    container_name: webappfinal
    image: luizfigueira/webappfinal:latest
    build:
      context: .
      dockerfile: WebAppFinal/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://*:83
    ports:
        - "83:83"
    depends_on:
        - webapifinal


  webapifinal:
    container_name: webapifinal
    image: luizfigueira/webapifinal:latest
    build:
      context: .
      dockerfile: WebApiFinal/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://*:84
    ports:
        - "84:84"
    depends_on:
        - sql-server
